FROM python:3.11-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8888

CMD ["streamlit", "run", "app.py", "--server.port=8888", "--server.address=0.0.0.0"]

